import type { User, Tenant, TenantSettings, ListParams } from '@/lib/api/types'
import { ApiError } from '@/lib/api/errors'
import { Collection, nextId } from './store'
import { makeCrud } from './fleet'
import { USERS, TENANTS } from './seed'
import { delay, deepClone } from './latency'

// Users without the mock password field. Drivers are managed under Drivers,
// not the Users admin screen, so they are excluded here.
const userRows: User[] = USERS.filter((u) => u.role !== 'driver').map(({ password: _pw, ...u }) => u)
const users = new Collection<User>(userRows, 'u', ['name', 'email'])

export const mockUsers = makeCrud(users)

/**
 * Tenants are platform-level (super admin), not tenant-scoped. Simple store
 * over all tenants; the CrudApi tenantId arg is ignored here.
 */
const tenantRows: (Tenant & { tenantId: string })[] = TENANTS.map((t) => ({ ...t, tenantId: t.id }))

export const mockTenants = {
  async list(_ignored: string, params: ListParams = {}) {
    const { page = 1, pageSize = 10, search = '', filters = {} } = params
    let items = tenantRows
    if (search.trim()) {
      const q = search.toLowerCase()
      items = items.filter((t) => t.name.toLowerCase().includes(q) || t.code.toLowerCase().includes(q))
    }
    if (filters.status) items = items.filter((t) => t.status === filters.status)
    const total = items.length
    const start = (page - 1) * pageSize
    return delay({ items: deepClone(items.slice(start, start + pageSize)), total, page, pageSize })
  },
  async get(_ignored: string, id: string) {
    const t = tenantRows.find((r) => r.id === id)
    if (!t) throw new ApiError('not_found', 'Tenant not found')
    return delay(deepClone(t))
  },
  async create(_ignored: string, data: Omit<Tenant, 'id' | 'createdAt'>) {
    const id = nextId('t')
    const row = { ...(data as Tenant), id, tenantId: id, createdAt: new Date().toISOString() }
    tenantRows.unshift(row)
    return delay(deepClone(row))
  },
  async update(_ignored: string, id: string, data: Partial<Tenant>) {
    const idx = tenantRows.findIndex((r) => r.id === id)
    if (idx === -1) throw new ApiError('not_found', 'Tenant not found')
    tenantRows[idx] = { ...tenantRows[idx], ...data, id, tenantId: id }
    return delay(deepClone(tenantRows[idx]))
  },
  async remove(_ignored: string, id: string) {
    const idx = tenantRows.findIndex((r) => r.id === id)
    if (idx !== -1) tenantRows.splice(idx, 1)
    return delay(undefined)
  },
}

// Per-tenant settings store.
const settingsByTenant: Record<string, TenantSettings> = {
  t1: {
    tenantId: 't1',
    timezone: 'Europe/London',
    workingDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
    amRouteTime: '08:00',
    pmRouteTime: '15:30',
    logoDataUrl: null,
    reportHeader: 'Northwind Transport Ltd — Compliance Report',
    reportFooter: 'Confidential · Generated by Transport Compliance Platform',
  },
}

function defaultSettings(tenantId: string): TenantSettings {
  return {
    tenantId,
    timezone: 'Europe/London',
    workingDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
    amRouteTime: '08:00',
    pmRouteTime: '15:30',
    logoDataUrl: null,
    reportHeader: '',
    reportFooter: '',
  }
}

export const mockSettings = {
  async get(tenantId: string): Promise<TenantSettings> {
    return delay(deepClone(settingsByTenant[tenantId] ?? defaultSettings(tenantId)))
  },
  async update(tenantId: string, data: Partial<TenantSettings>): Promise<TenantSettings> {
    const current = settingsByTenant[tenantId] ?? defaultSettings(tenantId)
    settingsByTenant[tenantId] = { ...current, ...data, tenantId }
    return delay(deepClone(settingsByTenant[tenantId]))
  },
}
