import type { User, TenantSettings } from '@/lib/api/types'
import { Collection } from './store'
import { makeCrud } from './fleet'
import { assertCan } from '@/lib/api/permissions'
import { USERS } from './seed'
import { delay, deepClone } from './latency'

// Users without the mock password field. Drivers are managed under Drivers,
// not the Users admin screen, so they are excluded here.
const userRows: User[] = USERS.filter((u) => u.role !== 'driver').map(({ password: _pw, ...u }) => u)
const users = new Collection<User>(userRows, 'u', ['name', 'email'])

// User management is admin-only — enforced at the API boundary.
export const mockUsers = makeCrud(users, 'users.manage')

// Per-tenant settings store.
const settingsByTenant: Record<string, TenantSettings> = {
  t1: {
    tenantId: 't1',
    timezone: 'Europe/London',
    workingDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
    amRouteTime: '08:00',
    pmRouteTime: '15:30',
    logoDataUrl: null,
    reportHeader: 'Northwind Transport Ltd — Compliance Report',
    reportFooter: 'Confidential · Generated by Transport Compliance Platform',
  },
}

function defaultSettings(tenantId: string): TenantSettings {
  return {
    tenantId,
    timezone: 'Europe/London',
    workingDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
    amRouteTime: '08:00',
    pmRouteTime: '15:30',
    logoDataUrl: null,
    reportHeader: '',
    reportFooter: '',
  }
}

export const mockSettings = {
  async get(tenantId: string): Promise<TenantSettings> {
    return delay(deepClone(settingsByTenant[tenantId] ?? defaultSettings(tenantId)))
  },
  async update(tenantId: string, data: Partial<TenantSettings>): Promise<TenantSettings> {
    assertCan('settings.manage') // admin-only
    const current = settingsByTenant[tenantId] ?? defaultSettings(tenantId)
    settingsByTenant[tenantId] = { ...current, ...data, tenantId }
    return delay(deepClone(settingsByTenant[tenantId]))
  },
}
